# Meta Data for SEO

## Homepage
title = "Tilly"
titleSeparator = "-"
titleAddition = "Soving the undecideables"
description = "Tilly是一个针对C语言的值流分析静态工具。"

## Open Graph
images = ["tilly.png"]
ogLocale = "zh_CN"
domainTLD = "tillycode.com"
titleHome = "Tilly"

## Twitter Cards
twitterSite = "@getdosunziping2016ks"
twitterCreator = "@sunziping2016"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Tilly"
schemaAuthor = "Sun Ziping"
schemaAuthorTwitter = "https://twitter.com/sunziping2016"
schemaAuthorGitHub = "https://twitter.com/sunziping2016"
schemaLocale = "zh-CN"
schemaLogo = "logo-tilly.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "tilly.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/sunziping2016"
schemaGitHub = "https://github.com/sunziping2016"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"
copyRight = "Copyright (c) 2020-2021 Henk Verlinde"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/sunziping2016/tilly-site"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = true
  collapsibleSidebar = false
